kind: pipeline
name: default

steps:
#  - name: test frontend
#    image: docker
#    environment:
#      RECAPTCHA_SITE_KEY:
#        from_secret: RECAPTCHA_SITE_KEY
#    commands:
#      - docker build -t test-frontend --build-arg RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY -f frontend/Dockerfile-test frontend
#      - docker run test-frontend
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#    when:
#      branch:
#        - master
#      event:
#        - pull_request
#
#  - name: test backend
#    image: docker
#    commands:
#      - docker build -t test-backend -f backend/Dockerfile-test backend
#      - docker run test-backend
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#    when:
#      branch:
#        - master
#      event:
#        - pull_request

#  - name: report code coverage
#    image: docker
#    environment:
#      CODECOV_TOKEN:
#        from_secret: CODECOV_TOKEN
#    commands:
#      - docker build -t report-coverage --build-arg CODECOV_TOKEN=$CODECOV_TOKEN -f Dockerfile-coverage .
#      - docker run report-coverage
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#    when:
#      branch:
#        - master
#      event:
#        - pull_request

# TODO REMOVE THIS STEP
#  - name: generate static assets
#    image: node:12.7.0-alpine
#    environment:
#      RECAPTCHA_SITE_KEY:
#        from_secret: RECAPTCHA_SITE_KEY
#    volumes:
#      - name: frontend-dep
#        path: /drone/src/frontend/node_modules
#    commands:
#      - apk add --no-cache bash git
#      - cd frontend
#      - yarn
#      - REACT_APP_RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY CI=true yarn build
#    when:
#      branch:
#        - master
#      event:
#        - push
  - name: build backend service
      image: docker/compose:1.24.1
      environment:
        DOCKERHUB_USERNAME:
          from_secret: DOCKERHUB_USERNAME
      commands:
        - cp .env.dist .env
        - docker-compose build backend
      volumes:
        - name: docker
          path: /var/run/docker.sock
      when:
        branch:
          - master
        event:
          - pull_request # push

  - name: build frontend service
    image: docker/compose:1.24.1
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      REACT_APP_RECAPTCHA_SITE_KEY:
        from_secret: RECAPTCHA_SITE_KEY
    commands:
      - cp .env.dist .env
      - REACT_APP_GIT_SHA=$DRONE_COMMIT docker-compose build frontend
    volumes:
      - name: docker
        path: /var/run/docker.sock
      - name: frontend-dep
        path: /drone/src/frontend/node_modules
    when:
      branch:
        - master
      event:
        - pull_request # push

  - name: publish to Docker registry
    image: docker
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DOCKERHUB_PASSWORD:
        from_secret: DOCKERHUB_PASSWORD
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - docker push $DOCKERHUB_USERNAME/short-frontend:test
      - docker push $DOCKERHUB_USERNAME/short-backend:test
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      branch:
        - master
      event:
        - pull_request

  - name: upload docker-compose.yml
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: SERVER_HOST
      username:
        from_secret: SERVER_USER
      password:
        from_secret: SERVER_PASSWORD
      port: 22
      command_timeout: 2m
      target:
        from_secret: DEST_DIR
      source:
        - docker-compose.yml
    when:
      branch:
        - production
      event:
        - push

  - name: deploy service
    image: appleboy/drone-ssh
    environment:
      DOCKERHUB_USERNAME:
        from_secret: DOCKERHUB_USERNAME
      DEST_DIR:
        from_secret: DEST_DIR
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_NAME:
        from_secret: DB_NAME
      RECAPTCHA_SECRET:
        from_secret: RECAPTCHA_SECRET
      GITHUB_CLIENT_ID:
        from_secret: GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET:
        from_secret: GITHUB_CLIENT_SECRET
      WEB_PORT:
        from_secret: WEB_PORT
      HTTP_API_PORT:
        from_secret: HTTP_API_PORT
      GRAPHQL_API_PORT:
        from_secret: GRAPHQL_API_PORT
      JWT_SECRET:
        from_secret: JWT_SECRET
      WEB_FRONTEND_URL:
        from_secret: WEB_FRONTEND_URL
      KEY_GEN_BUFFER_SIZE:
        from_secret: KEY_GEN_BUFFER_SIZE
      KEY_GEN_HOSTNAME:
        from_secret: KEY_GEN_HOSTNAME
      KEY_GEN_PORT:
        from_secret: KEY_GEN_PORT
    settings:
      host:
        from_secret: SERVER_HOST
      username:
        from_secret: SERVER_USER
      password:
        from_secret: SERVER_PASSWORD
      port: 22
      envs:
        - DOCKERHUB_USERNAME
        - DEST_DIR
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - RECAPTCHA_SECRET
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
        - JWT_SECRET
        - WEB_FRONTEND_URL
        - WEB_PORT
        - HTTP_API_PORT
        - GRAPHQL_API_PORT
        - KEY_GEN_BUFFER_SIZE
        - KEY_GEN_HOSTNAME
        - KEY_GEN_PORT
      script:
        - docker pull $DOCKERHUB_USERNAME/short-frontend
        - docker pull $DOCKERHUB_USERNAME/short-backend
        - cd $DEST_DIR;
          DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
          DB_USER=$DB_USER
          DB_PASSWORD=$DB_PASSWORD
          DB_NAME=$DB_NAME
          RECAPTCHA_SECRET=$RECAPTCHA_SECRET
          GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
          GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
          JWT_SECRET=$JWT_SECRET
          WEB_FRONTEND_URL=$WEB_FRONTEND_URL
          WEB_PORT=$WEB_PORT
          HTTP_API_PORT=$HTTP_API_PORT
          GRAPHQL_API_PORT=$GRAPHQL_API_PORT
          KEY_GEN_BUFFER_SIZE=$KEY_GEN_BUFFER_SIZE
          KEY_GEN_HOSTNAME=$KEY_GEN_HOSTNAME
          KEY_GEN_PORT=$KEY_GEN_PORT
          docker-compose up -d
    when:
      branch:
        - production
      event:
        - push
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: frontend-dep
    host:
      path: /drone/frontend-dep