language: node_js
node_js:
  - 12

services:
  - docker

script:
  - ./bin/test-web
  - DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME ./bin/test
  - ./bin/build-web
  - DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME ./bin/build

after_success:
  - ./bin/publish $DOCKER_HUB_USERNAME $DOCKER_HUB_PASSWORD