version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WWWROOT=${WWWROOT}
    command: ["./bin/wait-for-it", "db:80", "--", "./build/short", "start", "--www", WWWROOT]
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
volumes:
  db_data: