version: '3'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/short-frontend:latest
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - backend
  backend:
    image: ${DOCKERHUB_USERNAME}/short-backend:latest
    ports:
      - "${GRAPHQL_API_PORT}:8080"
      - "${HTTP_API_PORT}:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - WEB_FRONTEND_URL=${WEB_FRONTEND_URL}
      - KEY_GEN_BUFFER_SIZE=${KEY_GEN_BUFFER_SIZE}
      - KEY_GEN_HOSTNAME=${KEY_GEN_HOSTNAME}
      - KEY_GEN_PORT=${KEY_GEN_PORT}
    command: [
      "./scripts/wait-for-it", "-s", "-t", "0", "db:5432", "--",
      "./build/app", "start", "--migration", "app/adapter/migration"
    ]
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5400:5432
volumes:
  db_data: