apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: short-db-data
  namespace: staging
  labels:
    volume: db-data
    app: short
    tier: backend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
